[package]
name = "ssh-auth-github"
version = "0.1.0"
authors = ["Erik Dalén <erik.gustav.dalen@gmail.com>"]

[dependencies]
reqwest = "0.9.0"
serde_json = "1.0.28"
serde_derive = "1.0.79"
serde = "1.0.79"
