[package]
name = "ssh-auth-github"
version = "0.1.0"
authors = ["Erik Dalén <erik.gustav.dalen@gmail.com>"]

[dependencies]
reqwest = "0.8.5"
serde_json = "1.0.26"
serde_derive = "1.0.73"
serde = "1.0.73"
